# Generated by Django 5.0.4 on 2024-06-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0002_rename_password_of_website_passwordvault__password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordvault',
            old_name='_password',
            new_name='password_of_website',
        ),
    ]
